services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mongodb/mongodb-community-server:latest
    env_file: ".env"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
