services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mongo:latest
    env_file: ".env"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data: